/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // --------------------------------------------------------
        // PRIMITIVE TOKENS — Primitive palette
        // Usage: bg-primitive-gray-500, text-primitive-purple-300, etc.
        // --------------------------------------------------------
        primitive: {
          gray: {
            0:    'var(--primitive-gray-0)',
            50:   'var(--primitive-gray-50)',
            70:   'var(--primitive-gray-70)',
            100:  'var(--primitive-gray-100)',
            200:  'var(--primitive-gray-200)',
            300:  'var(--primitive-gray-300)',
            400:  'var(--primitive-gray-400)',
            500:  'var(--primitive-gray-500)',
            600:  'var(--primitive-gray-600)',
            700:  'var(--primitive-gray-700)',
            800:  'var(--primitive-gray-800)',
            900:  'var(--primitive-gray-900)',
            950:  'var(--primitive-gray-950)',
            1000: 'var(--primitive-gray-1000)',
          },
          'black-alpha': {
            0:    'var(--primitive-black-alpha-0)',
            50:   'var(--primitive-black-alpha-50)',
            70:   'var(--primitive-black-alpha-70)',
            100:  'var(--primitive-black-alpha-100)',
            200:  'var(--primitive-black-alpha-200)',
            300:  'var(--primitive-black-alpha-300)',
            400:  'var(--primitive-black-alpha-400)',
            500:  'var(--primitive-black-alpha-500)',
            600:  'var(--primitive-black-alpha-600)',
            700:  'var(--primitive-black-alpha-700)',
            800:  'var(--primitive-black-alpha-800)',
            900:  'var(--primitive-black-alpha-900)',
            950:  'var(--primitive-black-alpha-950)',
            1000: 'var(--primitive-black-alpha-1000)',
          },
          'white-alpha': {
            0:    'var(--primitive-white-alpha-0)',
            50:   'var(--primitive-white-alpha-50)',
            70:   'var(--primitive-white-alpha-70)',
            100:  'var(--primitive-white-alpha-100)',
            200:  'var(--primitive-white-alpha-200)',
            300:  'var(--primitive-white-alpha-300)',
            400:  'var(--primitive-white-alpha-400)',
            500:  'var(--primitive-white-alpha-500)',
            600:  'var(--primitive-white-alpha-600)',
            700:  'var(--primitive-white-alpha-700)',
            800:  'var(--primitive-white-alpha-800)',
            900:  'var(--primitive-white-alpha-900)',
            950:  'var(--primitive-white-alpha-950)',
            1000: 'var(--primitive-white-alpha-1000)',
          },
          indigo: {
            0:    'var(--primitive-indigo-0)',
            50:   'var(--primitive-indigo-50)',
            70:   'var(--primitive-indigo-70)',
            100:  'var(--primitive-indigo-100)',
            200:  'var(--primitive-indigo-200)',
            300:  'var(--primitive-indigo-300)',
            400:  'var(--primitive-indigo-400)',
            500:  'var(--primitive-indigo-500)',
            600:  'var(--primitive-indigo-600)',
            700:  'var(--primitive-indigo-700)',
            800:  'var(--primitive-indigo-800)',
            900:  'var(--primitive-indigo-900)',
            950:  'var(--primitive-indigo-950)',
            1000: 'var(--primitive-indigo-1000)',
          },
          purple: {
            0:    'var(--primitive-purple-0)',
            50:   'var(--primitive-purple-50)',
            70:   'var(--primitive-purple-70)',
            100:  'var(--primitive-purple-100)',
            200:  'var(--primitive-purple-200)',
            300:  'var(--primitive-purple-300)',
            400:  'var(--primitive-purple-400)',
            500:  'var(--primitive-purple-500)',
            600:  'var(--primitive-purple-600)',
            700:  'var(--primitive-purple-700)',
            800:  'var(--primitive-purple-800)',
            900:  'var(--primitive-purple-900)',
            950:  'var(--primitive-purple-950)',
            1000: 'var(--primitive-purple-1000)',
          },
          violet: {
            0:    'var(--primitive-violet-0)',
            50:   'var(--primitive-violet-50)',
            70:   'var(--primitive-violet-70)',
            100:  'var(--primitive-violet-100)',
            200:  'var(--primitive-violet-200)',
            300:  'var(--primitive-violet-300)',
            400:  'var(--primitive-violet-400)',
            500:  'var(--primitive-violet-500)',
            600:  'var(--primitive-violet-600)',
            700:  'var(--primitive-violet-700)',
            800:  'var(--primitive-violet-800)',
            900:  'var(--primitive-violet-900)',
            950:  'var(--primitive-violet-950)',
            1000: 'var(--primitive-violet-1000)',
          },
          pink: {
            0:    'var(--primitive-pink-0)',
            50:   'var(--primitive-pink-50)',
            70:   'var(--primitive-pink-70)',
            100:  'var(--primitive-pink-100)',
            200:  'var(--primitive-pink-200)',
            300:  'var(--primitive-pink-300)',
            400:  'var(--primitive-pink-400)',
            500:  'var(--primitive-pink-500)',
            600:  'var(--primitive-pink-600)',
            700:  'var(--primitive-pink-700)',
            800:  'var(--primitive-pink-800)',
            900:  'var(--primitive-pink-900)',
            950:  'var(--primitive-pink-950)',
            1000: 'var(--primitive-pink-1000)',
          },
          rose: {
            0:    'var(--primitive-rose-0)',
            50:   'var(--primitive-rose-50)',
            70:   'var(--primitive-rose-70)',
            100:  'var(--primitive-rose-100)',
            200:  'var(--primitive-rose-200)',
            300:  'var(--primitive-rose-300)',
            400:  'var(--primitive-rose-400)',
            500:  'var(--primitive-rose-500)',
            600:  'var(--primitive-rose-600)',
            700:  'var(--primitive-rose-700)',
            800:  'var(--primitive-rose-800)',
            900:  'var(--primitive-rose-900)',
            950:  'var(--primitive-rose-950)',
            1000: 'var(--primitive-rose-1000)',
          },
          'red-bright': {
            0:    'var(--primitive-red-bright-0)',
            50:   'var(--primitive-red-bright-50)',
            70:   'var(--primitive-red-bright-70)',
            100:  'var(--primitive-red-bright-100)',
            200:  'var(--primitive-red-bright-200)',
            300:  'var(--primitive-red-bright-300)',
            400:  'var(--primitive-red-bright-400)',
            500:  'var(--primitive-red-bright-500)',
            600:  'var(--primitive-red-bright-600)',
            700:  'var(--primitive-red-bright-700)',
            800:  'var(--primitive-red-bright-800)',
            900:  'var(--primitive-red-bright-900)',
            950:  'var(--primitive-red-bright-950)',
            1000: 'var(--primitive-red-bright-1000)',
          },
          'red-dark': {
            0:    'var(--primitive-red-dark-0)',
            50:   'var(--primitive-red-dark-50)',
            70:   'var(--primitive-red-dark-70)',
            100:  'var(--primitive-red-dark-100)',
            200:  'var(--primitive-red-dark-200)',
            300:  'var(--primitive-red-dark-300)',
            400:  'var(--primitive-red-dark-400)',
            500:  'var(--primitive-red-dark-500)',
            600:  'var(--primitive-red-dark-600)',
            700:  'var(--primitive-red-dark-700)',
            800:  'var(--primitive-red-dark-800)',
            900:  'var(--primitive-red-dark-900)',
            950:  'var(--primitive-red-dark-950)',
            1000: 'var(--primitive-red-dark-1000)',
          },
          'red-orange': {
            0:    'var(--primitive-red-orange-0)',
            50:   'var(--primitive-red-orange-50)',
            70:   'var(--primitive-red-orange-70)',
            100:  'var(--primitive-red-orange-100)',
            200:  'var(--primitive-red-orange-200)',
            300:  'var(--primitive-red-orange-300)',
            400:  'var(--primitive-red-orange-400)',
            500:  'var(--primitive-red-orange-500)',
            600:  'var(--primitive-red-orange-600)',
            700:  'var(--primitive-red-orange-700)',
            800:  'var(--primitive-red-orange-800)',
            900:  'var(--primitive-red-orange-900)',
            950:  'var(--primitive-red-orange-950)',
            1000: 'var(--primitive-red-orange-1000)',
          },
          orange: {
            0:    'var(--primitive-orange-0)',
            50:   'var(--primitive-orange-50)',
            70:   'var(--primitive-orange-70)',
            100:  'var(--primitive-orange-100)',
            200:  'var(--primitive-orange-200)',
            300:  'var(--primitive-orange-300)',
            400:  'var(--primitive-orange-400)',
            500:  'var(--primitive-orange-500)',
            600:  'var(--primitive-orange-600)',
            700:  'var(--primitive-orange-700)',
            800:  'var(--primitive-orange-800)',
            900:  'var(--primitive-orange-900)',
            950:  'var(--primitive-orange-950)',
            1000: 'var(--primitive-orange-1000)',
          },
          amber: {
            0:    'var(--primitive-amber-0)',
            50:   'var(--primitive-amber-50)',
            70:   'var(--primitive-amber-70)',
            100:  'var(--primitive-amber-100)',
            200:  'var(--primitive-amber-200)',
            300:  'var(--primitive-amber-300)',
            400:  'var(--primitive-amber-400)',
            500:  'var(--primitive-amber-500)',
            600:  'var(--primitive-amber-600)',
            700:  'var(--primitive-amber-700)',
            800:  'var(--primitive-amber-800)',
            900:  'var(--primitive-amber-900)',
            950:  'var(--primitive-amber-950)',
            1000: 'var(--primitive-amber-1000)',
          },
          yellow: {
            0:    'var(--primitive-yellow-0)',
            50:   'var(--primitive-yellow-50)',
            70:   'var(--primitive-yellow-70)',
            100:  'var(--primitive-yellow-100)',
            200:  'var(--primitive-yellow-200)',
            300:  'var(--primitive-yellow-300)',
            400:  'var(--primitive-yellow-400)',
            500:  'var(--primitive-yellow-500)',
            600:  'var(--primitive-yellow-600)',
            700:  'var(--primitive-yellow-700)',
            800:  'var(--primitive-yellow-800)',
            900:  'var(--primitive-yellow-900)',
            950:  'var(--primitive-yellow-950)',
            1000: 'var(--primitive-yellow-1000)',
          },
          lime: {
            0:    'var(--primitive-lime-0)',
            50:   'var(--primitive-lime-50)',
            70:   'var(--primitive-lime-70)',
            100:  'var(--primitive-lime-100)',
            200:  'var(--primitive-lime-200)',
            300:  'var(--primitive-lime-300)',
            400:  'var(--primitive-lime-400)',
            500:  'var(--primitive-lime-500)',
            600:  'var(--primitive-lime-600)',
            700:  'var(--primitive-lime-700)',
            800:  'var(--primitive-lime-800)',
            900:  'var(--primitive-lime-900)',
            950:  'var(--primitive-lime-950)',
            1000: 'var(--primitive-lime-1000)',
          },
          edamame: {
            0:    'var(--primitive-edamame-0)',
            50:   'var(--primitive-edamame-50)',
            70:   'var(--primitive-edamame-70)',
            100:  'var(--primitive-edamame-100)',
            200:  'var(--primitive-edamame-200)',
            300:  'var(--primitive-edamame-300)',
            400:  'var(--primitive-edamame-400)',
            500:  'var(--primitive-edamame-500)',
            600:  'var(--primitive-edamame-600)',
            700:  'var(--primitive-edamame-700)',
            800:  'var(--primitive-edamame-800)',
            900:  'var(--primitive-edamame-900)',
            950:  'var(--primitive-edamame-950)',
            1000: 'var(--primitive-edamame-1000)',
          },
          green: {
            0:    'var(--primitive-green-0)',
            50:   'var(--primitive-green-50)',
            70:   'var(--primitive-green-70)',
            100:  'var(--primitive-green-100)',
            200:  'var(--primitive-green-200)',
            300:  'var(--primitive-green-300)',
            400:  'var(--primitive-green-400)',
            500:  'var(--primitive-green-500)',
            600:  'var(--primitive-green-600)',
            700:  'var(--primitive-green-700)',
            800:  'var(--primitive-green-800)',
            900:  'var(--primitive-green-900)',
            950:  'var(--primitive-green-950)',
            1000: 'var(--primitive-green-1000)',
          },
          forest: {
            0:    'var(--primitive-forest-0)',
            50:   'var(--primitive-forest-50)',
            70:   'var(--primitive-forest-70)',
            100:  'var(--primitive-forest-100)',
            200:  'var(--primitive-forest-200)',
            300:  'var(--primitive-forest-300)',
            400:  'var(--primitive-forest-400)',
            500:  'var(--primitive-forest-500)',
            600:  'var(--primitive-forest-600)',
            700:  'var(--primitive-forest-700)',
            800:  'var(--primitive-forest-800)',
            900:  'var(--primitive-forest-900)',
            950:  'var(--primitive-forest-950)',
            1000: 'var(--primitive-forest-1000)',
          },
          emerald: {
            0:    'var(--primitive-emerald-0)',
            50:   'var(--primitive-emerald-50)',
            70:   'var(--primitive-emerald-70)',
            100:  'var(--primitive-emerald-100)',
            200:  'var(--primitive-emerald-200)',
            300:  'var(--primitive-emerald-300)',
            400:  'var(--primitive-emerald-400)',
            500:  'var(--primitive-emerald-500)',
            600:  'var(--primitive-emerald-600)',
            700:  'var(--primitive-emerald-700)',
            800:  'var(--primitive-emerald-800)',
            900:  'var(--primitive-emerald-900)',
            950:  'var(--primitive-emerald-950)',
            1000: 'var(--primitive-emerald-1000)',
          },
          teal: {
            0:    'var(--primitive-teal-0)',
            50:   'var(--primitive-teal-50)',
            70:   'var(--primitive-teal-70)',
            100:  'var(--primitive-teal-100)',
            200:  'var(--primitive-teal-200)',
            300:  'var(--primitive-teal-300)',
            400:  'var(--primitive-teal-400)',
            500:  'var(--primitive-teal-500)',
            600:  'var(--primitive-teal-600)',
            700:  'var(--primitive-teal-700)',
            800:  'var(--primitive-teal-800)',
            900:  'var(--primitive-teal-900)',
            950:  'var(--primitive-teal-950)',
            1000: 'var(--primitive-teal-1000)',
          },
          cyan: {
            0:    'var(--primitive-cyan-0)',
            50:   'var(--primitive-cyan-50)',
            70:   'var(--primitive-cyan-70)',
            100:  'var(--primitive-cyan-100)',
            200:  'var(--primitive-cyan-200)',
            300:  'var(--primitive-cyan-300)',
            400:  'var(--primitive-cyan-400)',
            500:  'var(--primitive-cyan-500)',
            600:  'var(--primitive-cyan-600)',
            700:  'var(--primitive-cyan-700)',
            800:  'var(--primitive-cyan-800)',
            900:  'var(--primitive-cyan-900)',
            950:  'var(--primitive-cyan-950)',
            1000: 'var(--primitive-cyan-1000)',
          },
          sky: {
            0:    'var(--primitive-sky-0)',
            50:   'var(--primitive-sky-50)',
            70:   'var(--primitive-sky-70)',
            100:  'var(--primitive-sky-100)',
            200:  'var(--primitive-sky-200)',
            300:  'var(--primitive-sky-300)',
            400:  'var(--primitive-sky-400)',
            500:  'var(--primitive-sky-500)',
            600:  'var(--primitive-sky-600)',
            700:  'var(--primitive-sky-700)',
            800:  'var(--primitive-sky-800)',
            900:  'var(--primitive-sky-900)',
            950:  'var(--primitive-sky-950)',
            1000: 'var(--primitive-sky-1000)',
          },
          blue: {
            0:    'var(--primitive-blue-0)',
            50:   'var(--primitive-blue-50)',
            70:   'var(--primitive-blue-70)',
            100:  'var(--primitive-blue-100)',
            200:  'var(--primitive-blue-200)',
            300:  'var(--primitive-blue-300)',
            400:  'var(--primitive-blue-400)',
            500:  'var(--primitive-blue-500)',
            600:  'var(--primitive-blue-600)',
            700:  'var(--primitive-blue-700)',
            800:  'var(--primitive-blue-800)',
            900:  'var(--primitive-blue-900)',
            950:  'var(--primitive-blue-950)',
            1000: 'var(--primitive-blue-1000)',
          },
        },

        // --------------------------------------------------------
        // SEMANTIC TOKENS — Semantic colors (theme-aware via data-theme)
        // Usage: bg-semantic-emphasized-purple-500, text-semantic-text-on-bright-800
        // Requires a [data-theme="light"] or [data-theme="dark"]
        // ancestor element to resolve correctly.
        // --------------------------------------------------------
        semantic: {
          'emphasized-purple': {
            50:  'var(--semantic-emphasized-purple-50)',
            100: 'var(--semantic-emphasized-purple-100)',
            200: 'var(--semantic-emphasized-purple-200)',
            300: 'var(--semantic-emphasized-purple-300)',
            400: 'var(--semantic-emphasized-purple-400)',
            500: 'var(--semantic-emphasized-purple-500)',
            600: 'var(--semantic-emphasized-purple-600)',
            700: 'var(--semantic-emphasized-purple-700)',
            800: 'var(--semantic-emphasized-purple-800)',
            900: 'var(--semantic-emphasized-purple-900)',
          },
          'emphasized-blue': {
            50:  'var(--semantic-emphasized-blue-50)',
            100: 'var(--semantic-emphasized-blue-100)',
            200: 'var(--semantic-emphasized-blue-200)',
            300: 'var(--semantic-emphasized-blue-300)',
            400: 'var(--semantic-emphasized-blue-400)',
            500: 'var(--semantic-emphasized-blue-500)',
            600: 'var(--semantic-emphasized-blue-600)',
            700: 'var(--semantic-emphasized-blue-700)',
            800: 'var(--semantic-emphasized-blue-800)',
            900: 'var(--semantic-emphasized-blue-900)',
          },
          'emphasized-orange': {
            50:  'var(--semantic-emphasized-orange-50)',
            100: 'var(--semantic-emphasized-orange-100)',
            200: 'var(--semantic-emphasized-orange-200)',
            300: 'var(--semantic-emphasized-orange-300)',
            400: 'var(--semantic-emphasized-orange-400)',
            500: 'var(--semantic-emphasized-orange-500)',
            600: 'var(--semantic-emphasized-orange-600)',
            700: 'var(--semantic-emphasized-orange-700)',
            800: 'var(--semantic-emphasized-orange-800)',
            900: 'var(--semantic-emphasized-orange-900)',
          },
          success: {
            50:  'var(--semantic-success-50)',
            100: 'var(--semantic-success-100)',
            200: 'var(--semantic-success-200)',
            300: 'var(--semantic-success-300)',
            400: 'var(--semantic-success-400)',
            500: 'var(--semantic-success-500)',
            600: 'var(--semantic-success-600)',
            700: 'var(--semantic-success-700)',
            800: 'var(--semantic-success-800)',
            900: 'var(--semantic-success-900)',
          },
          warning: {
            50:  'var(--semantic-warning-50)',
            100: 'var(--semantic-warning-100)',
            200: 'var(--semantic-warning-200)',
            300: 'var(--semantic-warning-300)',
            400: 'var(--semantic-warning-400)',
            500: 'var(--semantic-warning-500)',
            600: 'var(--semantic-warning-600)',
            700: 'var(--semantic-warning-700)',
            800: 'var(--semantic-warning-800)',
            900: 'var(--semantic-warning-900)',
          },
          error: {
            50:  'var(--semantic-error-50)',
            100: 'var(--semantic-error-100)',
            200: 'var(--semantic-error-200)',
            300: 'var(--semantic-error-300)',
            400: 'var(--semantic-error-400)',
            500: 'var(--semantic-error-500)',
            600: 'var(--semantic-error-600)',
            700: 'var(--semantic-error-700)',
            800: 'var(--semantic-error-800)',
            900: 'var(--semantic-error-900)',
          },
          neutral: {
            solid: {
              0:   'var(--semantic-neutral-solid-0)',
              50:  'var(--semantic-neutral-solid-50)',
              70:  'var(--semantic-neutral-solid-70)',
              100: 'var(--semantic-neutral-solid-100)',
              200: 'var(--semantic-neutral-solid-200)',
              300: 'var(--semantic-neutral-solid-300)',
              400: 'var(--semantic-neutral-solid-400)',
              500: 'var(--semantic-neutral-solid-500)',
              600: 'var(--semantic-neutral-solid-600)',
              700: 'var(--semantic-neutral-solid-700)',
              800: 'var(--semantic-neutral-solid-800)',
              900: 'var(--semantic-neutral-solid-900)',
              950: 'var(--semantic-neutral-solid-950)',
            },
            'black-alpha': {
              0:   'var(--semantic-neutral-black-alpha-0)',
              50:  'var(--semantic-neutral-black-alpha-50)',
              70:  'var(--semantic-neutral-black-alpha-70)',
              100: 'var(--semantic-neutral-black-alpha-100)',
              200: 'var(--semantic-neutral-black-alpha-200)',
              300: 'var(--semantic-neutral-black-alpha-300)',
              400: 'var(--semantic-neutral-black-alpha-400)',
              600: 'var(--semantic-neutral-black-alpha-600)',
              800: 'var(--semantic-neutral-black-alpha-800)',
              950: 'var(--semantic-neutral-black-alpha-950)',
            },
            'white-alpha': {
              0:   'var(--semantic-neutral-white-alpha-0)',
              50:  'var(--semantic-neutral-white-alpha-50)',
              70:  'var(--semantic-neutral-white-alpha-70)',
              100: 'var(--semantic-neutral-white-alpha-100)',
              200: 'var(--semantic-neutral-white-alpha-200)',
              300: 'var(--semantic-neutral-white-alpha-300)',
              400: 'var(--semantic-neutral-white-alpha-400)',
              600: 'var(--semantic-neutral-white-alpha-600)',
              800: 'var(--semantic-neutral-white-alpha-800)',
              950: 'var(--semantic-neutral-white-alpha-950)',
            },
          },
          background: {
            0:  'var(--semantic-background-0)',
            50: 'var(--semantic-background-50)',
            70: 'var(--semantic-background-70)',
          },
          divider: {
            solid: {
              50:  'var(--semantic-divider-solid-50)',
              70:  'var(--semantic-divider-solid-70)',
              100: 'var(--semantic-divider-solid-100)',
              200: 'var(--semantic-divider-solid-200)',
              300: 'var(--semantic-divider-solid-300)',
            },
            alpha: {
              50:  'var(--semantic-divider-alpha-50)',
              70:  'var(--semantic-divider-alpha-70)',
              100: 'var(--semantic-divider-alpha-100)',
              200: 'var(--semantic-divider-alpha-200)',
              300: 'var(--semantic-divider-alpha-300)',
            },
          },
          text: {
            'on-bright': {
              400: 'var(--semantic-text-on-bright-400)',
              600: 'var(--semantic-text-on-bright-600)',
              800: 'var(--semantic-text-on-bright-800)',
              900: 'var(--semantic-text-on-bright-900)',
              950: 'var(--semantic-text-on-bright-950)',
            },
            'on-dim': {
              400: 'var(--semantic-text-on-dim-400)',
              600: 'var(--semantic-text-on-dim-600)',
              800: 'var(--semantic-text-on-dim-800)',
              900: 'var(--semantic-text-on-dim-900)',
              950: 'var(--semantic-text-on-dim-950)',
            },
          },
          state: {
            'on-bright': {
              50:  'var(--semantic-state-on-bright-50)',
              70:  'var(--semantic-state-on-bright-70)',
              100: 'var(--semantic-state-on-bright-100)',
            },
            'on-dim': {
              50:  'var(--semantic-state-on-dim-50)',
              70:  'var(--semantic-state-on-dim-70)',
              100: 'var(--semantic-state-on-dim-100)',
            },
          },
        },
      },

      // --------------------------------------------------------
      // SPACING TOKENS
      // Usage: p-4 → 16px, gap-6 → 24px, m-0.5 → 2px, etc.
      // --------------------------------------------------------
      spacing: {
        px:    'var(--primitive-spacing-px)',
        '0':   'var(--primitive-spacing-0)',
        '0.5': 'var(--primitive-spacing-0\\.5)',
        '1':   'var(--primitive-spacing-1)',
        '1.5': 'var(--primitive-spacing-1\\.5)',
        '2':   'var(--primitive-spacing-2)',
        '2.5': 'var(--primitive-spacing-2\\.5)',
        '3':   'var(--primitive-spacing-3)',
        '3.5': 'var(--primitive-spacing-3\\.5)',
        '4':   'var(--primitive-spacing-4)',
        '5':   'var(--primitive-spacing-5)',
        '6':   'var(--primitive-spacing-6)',
        '7':   'var(--primitive-spacing-7)',
        '8':   'var(--primitive-spacing-8)',
        '9':   'var(--primitive-spacing-9)',
        '10':  'var(--primitive-spacing-10)',
        '11':  'var(--primitive-spacing-11)',
        '12':  'var(--primitive-spacing-12)',
        '14':  'var(--primitive-spacing-14)',
        '16':  'var(--primitive-spacing-16)',
        '18':  'var(--primitive-spacing-18)',
        '20':  'var(--primitive-spacing-20)',
        '24':  'var(--primitive-spacing-24)',
        '28':  'var(--primitive-spacing-28)',
        '32':  'var(--primitive-spacing-32)',
        '36':  'var(--primitive-spacing-36)',
        '40':  'var(--primitive-spacing-40)',
        '44':  'var(--primitive-spacing-44)',
        '48':  'var(--primitive-spacing-48)',
        '52':  'var(--primitive-spacing-52)',
        '56':  'var(--primitive-spacing-56)',
        '60':  'var(--primitive-spacing-60)',
        '64':  'var(--primitive-spacing-64)',
        '72':  'var(--primitive-spacing-72)',
        '80':  'var(--primitive-spacing-80)',
        '96':  'var(--primitive-spacing-96)',
      },

      // --------------------------------------------------------
      // RADIUS TOKENS
      // Usage: rounded-2 → 8px, rounded-4 → 16px, etc.
      // --------------------------------------------------------
      borderRadius: {
        px:    'var(--primitive-radius-px)',
        '0':   'var(--primitive-radius-0)',
        '0.5': 'var(--primitive-radius-0\\.5)',
        '1':   'var(--primitive-radius-1)',
        '1.5': 'var(--primitive-radius-1\\.5)',
        '2':   'var(--primitive-radius-2)',
        '2.5': 'var(--primitive-radius-2\\.5)',
        '3':   'var(--primitive-radius-3)',
        '3.5': 'var(--primitive-radius-3\\.5)',
        '4':   'var(--primitive-radius-4)',
        '5':   'var(--primitive-radius-5)',
        '6':   'var(--primitive-radius-6)',
        '7':   'var(--primitive-radius-7)',
        '8':   'var(--primitive-radius-8)',
        '9':   'var(--primitive-radius-9)',
        '10':  'var(--primitive-radius-10)',
        '11':  'var(--primitive-radius-11)',
        '12':  'var(--primitive-radius-12)',
        '14':  'var(--primitive-radius-14)',
        '16':  'var(--primitive-radius-16)',
        '18':  'var(--primitive-radius-18)',
        '20':  'var(--primitive-radius-20)',
        '24':  'var(--primitive-radius-24)',
      },

      // --------------------------------------------------------
      // TYPOGRAPHY TOKENS — now generated via plugin below as
      //   typography-{size}-{weight} utilities
      //   (e.g. typography-40-bold, typography-16-semibold)
      // See plugins[] at the bottom of this file.
      // --------------------------------------------------------

      // --------------------------------------------------------
      // FONT FAMILY TOKEN
      // Usage: font-geist
      // --------------------------------------------------------
      fontFamily: {
        geist: ['Geist Sans', 'sans-serif'],
      },

      // --------------------------------------------------------
      // MOTION TOKENS — Duration & Easing
      // Usage: duration-fast, ease-enter, etc.
      // --------------------------------------------------------
      transitionDuration: {
        instant: 'var(--semantic-duration-instant)',
        fast:    'var(--semantic-duration-fast)',
        medium:  'var(--semantic-duration-medium)',
        normal:  'var(--semantic-duration-normal)',
        slow:    'var(--semantic-duration-slow)',
        slower:  'var(--semantic-duration-slower)',
      },
      transitionTimingFunction: {
        enter:  'var(--semantic-easing-enter)',
        exit:   'var(--semantic-easing-exit)',
        move:   'var(--semantic-easing-move)',
        linear: 'var(--semantic-easing-linear)',
      },
      animationDuration: {
        instant: 'var(--semantic-duration-instant)',
        fast:    'var(--semantic-duration-fast)',
        medium:  'var(--semantic-duration-medium)',
        normal:  'var(--semantic-duration-normal)',
        slow:    'var(--semantic-duration-slow)',
        slower:  'var(--semantic-duration-slower)',
      },
      animationTimingFunction: {
        enter:  'var(--semantic-easing-enter)',
        exit:   'var(--semantic-easing-exit)',
        move:   'var(--semantic-easing-move)',
        linear: 'var(--semantic-easing-linear)',
      },

    },
  },
  plugins: [
    require('tailwindcss-animate'),
    // --------------------------------------------------------
    // TYPOGRAPHY TOKENS — Composite (size + weight)
    // Source: Figma Design-System-v3, node 6089-461
    // Font: Pretendard Variable
    // Usage: typography-{size}-{weight}
    //   e.g. typography-40-bold, typography-16-semibold, typography-14-regular
    // Each class sets: font-size + line-height + letter-spacing + font-weight
    //
    // Uses a custom plugin (addUtilities) instead of fontSize config
    // so that the "typography-" prefix does not conflict with Tailwind's
    // built-in "text-" prefix used for text color utilities.
    // --------------------------------------------------------
    function({ addUtilities }) {
      const tokens = {
        // size 64 — 4rem / 72px / -0.012em
        '64-bold':     { fontSize: 'var(--text-size-64)', lineHeight: 'var(--text-lh-64)', letterSpacing: 'var(--text-ls-64)', fontWeight: '700' },
        '64-semibold': { fontSize: 'var(--text-size-64)', lineHeight: 'var(--text-lh-64)', letterSpacing: 'var(--text-ls-64)', fontWeight: '600' },
        '64-medium':   { fontSize: 'var(--text-size-64)', lineHeight: 'var(--text-lh-64)', letterSpacing: 'var(--text-ls-64)', fontWeight: '500' },
        '64-regular':  { fontSize: 'var(--text-size-64)', lineHeight: 'var(--text-lh-64)', letterSpacing: 'var(--text-ls-64)', fontWeight: '400' },
        // size 48 — 3rem / 56px / -0.012em
        '48-bold':     { fontSize: 'var(--text-size-48)', lineHeight: 'var(--text-lh-48)', letterSpacing: 'var(--text-ls-48)', fontWeight: '700' },
        '48-semibold': { fontSize: 'var(--text-size-48)', lineHeight: 'var(--text-lh-48)', letterSpacing: 'var(--text-ls-48)', fontWeight: '600' },
        '48-medium':   { fontSize: 'var(--text-size-48)', lineHeight: 'var(--text-lh-48)', letterSpacing: 'var(--text-ls-48)', fontWeight: '500' },
        '48-regular':  { fontSize: 'var(--text-size-48)', lineHeight: 'var(--text-lh-48)', letterSpacing: 'var(--text-ls-48)', fontWeight: '400' },
        // size 40 — 2.5rem / 48px / -0.012em
        '40-bold':     { fontSize: 'var(--text-size-40)', lineHeight: 'var(--text-lh-40)', letterSpacing: 'var(--text-ls-40)', fontWeight: '700' },
        '40-semibold': { fontSize: 'var(--text-size-40)', lineHeight: 'var(--text-lh-40)', letterSpacing: 'var(--text-ls-40)', fontWeight: '600' },
        '40-medium':   { fontSize: 'var(--text-size-40)', lineHeight: 'var(--text-lh-40)', letterSpacing: 'var(--text-ls-40)', fontWeight: '500' },
        '40-regular':  { fontSize: 'var(--text-size-40)', lineHeight: 'var(--text-lh-40)', letterSpacing: 'var(--text-ls-40)', fontWeight: '400' },
        // size 32 — 2rem / 38px / -0.012em
        '32-bold':     { fontSize: 'var(--text-size-32)', lineHeight: 'var(--text-lh-32)', letterSpacing: 'var(--text-ls-32)', fontWeight: '700' },
        '32-semibold': { fontSize: 'var(--text-size-32)', lineHeight: 'var(--text-lh-32)', letterSpacing: 'var(--text-ls-32)', fontWeight: '600' },
        '32-medium':   { fontSize: 'var(--text-size-32)', lineHeight: 'var(--text-lh-32)', letterSpacing: 'var(--text-ls-32)', fontWeight: '500' },
        '32-regular':  { fontSize: 'var(--text-size-32)', lineHeight: 'var(--text-lh-32)', letterSpacing: 'var(--text-ls-32)', fontWeight: '400' },
        // size 28 — 1.75rem / 34px / -0.010em
        '28-bold':     { fontSize: 'var(--text-size-28)', lineHeight: 'var(--text-lh-28)', letterSpacing: 'var(--text-ls-28)', fontWeight: '700' },
        '28-semibold': { fontSize: 'var(--text-size-28)', lineHeight: 'var(--text-lh-28)', letterSpacing: 'var(--text-ls-28)', fontWeight: '600' },
        '28-medium':   { fontSize: 'var(--text-size-28)', lineHeight: 'var(--text-lh-28)', letterSpacing: 'var(--text-ls-28)', fontWeight: '500' },
        '28-regular':  { fontSize: 'var(--text-size-28)', lineHeight: 'var(--text-lh-28)', letterSpacing: 'var(--text-ls-28)', fontWeight: '400' },
        // size 24 — 1.5rem / 30px / -0.008em
        '24-bold':     { fontSize: 'var(--text-size-24)', lineHeight: 'var(--text-lh-24)', letterSpacing: 'var(--text-ls-24)', fontWeight: '700' },
        '24-semibold': { fontSize: 'var(--text-size-24)', lineHeight: 'var(--text-lh-24)', letterSpacing: 'var(--text-ls-24)', fontWeight: '600' },
        '24-medium':   { fontSize: 'var(--text-size-24)', lineHeight: 'var(--text-lh-24)', letterSpacing: 'var(--text-ls-24)', fontWeight: '500' },
        '24-regular':  { fontSize: 'var(--text-size-24)', lineHeight: 'var(--text-lh-24)', letterSpacing: 'var(--text-ls-24)', fontWeight: '400' },
        // size 22 — 1.375rem / 28px / -0.016em
        '22-bold':     { fontSize: 'var(--text-size-22)', lineHeight: 'var(--text-lh-22)', letterSpacing: 'var(--text-ls-22)', fontWeight: '700' },
        '22-semibold': { fontSize: 'var(--text-size-22)', lineHeight: 'var(--text-lh-22)', letterSpacing: 'var(--text-ls-22)', fontWeight: '600' },
        '22-medium':   { fontSize: 'var(--text-size-22)', lineHeight: 'var(--text-lh-22)', letterSpacing: 'var(--text-ls-22)', fontWeight: '500' },
        '22-regular':  { fontSize: 'var(--text-size-22)', lineHeight: 'var(--text-lh-22)', letterSpacing: 'var(--text-ls-22)', fontWeight: '400' },
        // size 20 — 1.25rem / 28px / -0.024em
        '20-bold':     { fontSize: 'var(--text-size-20)', lineHeight: 'var(--text-lh-20)', letterSpacing: 'var(--text-ls-20)', fontWeight: '700' },
        '20-semibold': { fontSize: 'var(--text-size-20)', lineHeight: 'var(--text-lh-20)', letterSpacing: 'var(--text-ls-20)', fontWeight: '600' },
        '20-medium':   { fontSize: 'var(--text-size-20)', lineHeight: 'var(--text-lh-20)', letterSpacing: 'var(--text-ls-20)', fontWeight: '500' },
        '20-regular':  { fontSize: 'var(--text-size-20)', lineHeight: 'var(--text-lh-20)', letterSpacing: 'var(--text-ls-20)', fontWeight: '400' },
        // size 18 — 1.125rem / 28px / -0.012em
        '18-bold':     { fontSize: 'var(--text-size-18)', lineHeight: 'var(--text-lh-18)', letterSpacing: 'var(--text-ls-18)', fontWeight: '700' },
        '18-semibold': { fontSize: 'var(--text-size-18)', lineHeight: 'var(--text-lh-18)', letterSpacing: 'var(--text-ls-18)', fontWeight: '600' },
        '18-medium':   { fontSize: 'var(--text-size-18)', lineHeight: 'var(--text-lh-18)', letterSpacing: 'var(--text-ls-18)', fontWeight: '500' },
        '18-regular':  { fontSize: 'var(--text-size-18)', lineHeight: 'var(--text-lh-18)', letterSpacing: 'var(--text-ls-18)', fontWeight: '400' },
        // size 17 — 1.0625rem / 24px / -0.010em
        '17-bold':     { fontSize: 'var(--text-size-17)', lineHeight: 'var(--text-lh-17)', letterSpacing: 'var(--text-ls-17)', fontWeight: '700' },
        '17-semibold': { fontSize: 'var(--text-size-17)', lineHeight: 'var(--text-lh-17)', letterSpacing: 'var(--text-ls-17)', fontWeight: '600' },
        '17-medium':   { fontSize: 'var(--text-size-17)', lineHeight: 'var(--text-lh-17)', letterSpacing: 'var(--text-ls-17)', fontWeight: '500' },
        '17-regular':  { fontSize: 'var(--text-size-17)', lineHeight: 'var(--text-lh-17)', letterSpacing: 'var(--text-ls-17)', fontWeight: '400' },
        // size 16 — 1rem / 24px / -0.009em
        '16-bold':     { fontSize: 'var(--text-size-16)', lineHeight: 'var(--text-lh-16)', letterSpacing: 'var(--text-ls-16)', fontWeight: '700' },
        '16-semibold': { fontSize: 'var(--text-size-16)', lineHeight: 'var(--text-lh-16)', letterSpacing: 'var(--text-ls-16)', fontWeight: '600' },
        '16-medium':   { fontSize: 'var(--text-size-16)', lineHeight: 'var(--text-lh-16)', letterSpacing: 'var(--text-ls-16)', fontWeight: '500' },
        '16-regular':  { fontSize: 'var(--text-size-16)', lineHeight: 'var(--text-lh-16)', letterSpacing: 'var(--text-ls-16)', fontWeight: '400' },
        // size 15 — 0.9375rem / 24px / -0.004em
        '15-bold':     { fontSize: 'var(--text-size-15)', lineHeight: 'var(--text-lh-15)', letterSpacing: 'var(--text-ls-15)', fontWeight: '700' },
        '15-semibold': { fontSize: 'var(--text-size-15)', lineHeight: 'var(--text-lh-15)', letterSpacing: 'var(--text-ls-15)', fontWeight: '600' },
        '15-medium':   { fontSize: 'var(--text-size-15)', lineHeight: 'var(--text-lh-15)', letterSpacing: 'var(--text-ls-15)', fontWeight: '500' },
        '15-regular':  { fontSize: 'var(--text-size-15)', lineHeight: 'var(--text-lh-15)', letterSpacing: 'var(--text-ls-15)', fontWeight: '400' },
        // size 14 — 0.875rem / 20px / 0em
        '14-bold':     { fontSize: 'var(--text-size-14)', lineHeight: 'var(--text-lh-14)', letterSpacing: 'var(--text-ls-14)', fontWeight: '700' },
        '14-semibold': { fontSize: 'var(--text-size-14)', lineHeight: 'var(--text-lh-14)', letterSpacing: 'var(--text-ls-14)', fontWeight: '600' },
        '14-medium':   { fontSize: 'var(--text-size-14)', lineHeight: 'var(--text-lh-14)', letterSpacing: 'var(--text-ls-14)', fontWeight: '500' },
        '14-regular':  { fontSize: 'var(--text-size-14)', lineHeight: 'var(--text-lh-14)', letterSpacing: 'var(--text-ls-14)', fontWeight: '400' },
        // size 13 — 0.8125rem / 16px / 0em
        '13-bold':     { fontSize: 'var(--text-size-13)', lineHeight: 'var(--text-lh-13)', letterSpacing: 'var(--text-ls-13)', fontWeight: '700' },
        '13-semibold': { fontSize: 'var(--text-size-13)', lineHeight: 'var(--text-lh-13)', letterSpacing: 'var(--text-ls-13)', fontWeight: '600' },
        '13-medium':   { fontSize: 'var(--text-size-13)', lineHeight: 'var(--text-lh-13)', letterSpacing: 'var(--text-ls-13)', fontWeight: '500' },
        '13-regular':  { fontSize: 'var(--text-size-13)', lineHeight: 'var(--text-lh-13)', letterSpacing: 'var(--text-ls-13)', fontWeight: '400' },
        // size 12 — 0.75rem / 16px / 0em
        '12-bold':     { fontSize: 'var(--text-size-12)', lineHeight: 'var(--text-lh-12)', letterSpacing: 'var(--text-ls-12)', fontWeight: '700' },
        '12-semibold': { fontSize: 'var(--text-size-12)', lineHeight: 'var(--text-lh-12)', letterSpacing: 'var(--text-ls-12)', fontWeight: '600' },
        '12-medium':   { fontSize: 'var(--text-size-12)', lineHeight: 'var(--text-lh-12)', letterSpacing: 'var(--text-ls-12)', fontWeight: '500' },
        '12-regular':  { fontSize: 'var(--text-size-12)', lineHeight: 'var(--text-lh-12)', letterSpacing: 'var(--text-ls-12)', fontWeight: '400' },
        // size 11 — 0.6875rem / 12px / 0em
        '11-bold':     { fontSize: 'var(--text-size-11)', lineHeight: 'var(--text-lh-11)', letterSpacing: 'var(--text-ls-11)', fontWeight: '700' },
        '11-semibold': { fontSize: 'var(--text-size-11)', lineHeight: 'var(--text-lh-11)', letterSpacing: 'var(--text-ls-11)', fontWeight: '600' },
        '11-medium':   { fontSize: 'var(--text-size-11)', lineHeight: 'var(--text-lh-11)', letterSpacing: 'var(--text-ls-11)', fontWeight: '500' },
        '11-regular':  { fontSize: 'var(--text-size-11)', lineHeight: 'var(--text-lh-11)', letterSpacing: 'var(--text-ls-11)', fontWeight: '400' },
        // size 10 — 0.625rem / 12px / 0em
        '10-bold':     { fontSize: 'var(--text-size-10)', lineHeight: 'var(--text-lh-10)', letterSpacing: 'var(--text-ls-10)', fontWeight: '700' },
        '10-semibold': { fontSize: 'var(--text-size-10)', lineHeight: 'var(--text-lh-10)', letterSpacing: 'var(--text-ls-10)', fontWeight: '600' },
        '10-medium':   { fontSize: 'var(--text-size-10)', lineHeight: 'var(--text-lh-10)', letterSpacing: 'var(--text-ls-10)', fontWeight: '500' },
        '10-regular':  { fontSize: 'var(--text-size-10)', lineHeight: 'var(--text-lh-10)', letterSpacing: 'var(--text-ls-10)', fontWeight: '400' },
      }
      const utilities = {}
      for (const [key, value] of Object.entries(tokens)) {
        utilities[`.typography-${key}`] = {
          'font-size': value.fontSize,
          'line-height': value.lineHeight,
          'letter-spacing': value.letterSpacing,
          'font-weight': value.fontWeight,
        }
      }
      addUtilities(utilities)
    },
  ],
}
